[package]
name = "desktop_app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tui = "0.19"
crossterm = "0.25"
wmctrl = "0.1.7"
image = "0.24.5"
signal-hook = "0.3.14"